<script setup lang="ts">
import { reactive, ref, watch } from 'vue';
import UWindow from '@/components/UWindow.vue';
import { downloadStorageUrl, queryUrlMetadata } from '@/api/storageContent';
import { gettext } from '@/locale';
import { formatBytes, textValue } from '@/utils/pveFormat';
const model = defineModel<boolean>({ required: true });
const props = defineProps<{ node: string; storage: string; content: string }>();
const emit = defineEmits<{ task: [upid: string] }>();
const loading = ref(false); const form = reactive({ url: '', filename: '', size: 0, mimetype: '', checksumAlgorithm: '__default__', checksum: '', verifyCertificates: true, compression: '__default__' });
function clearMetadata() { form.size = 0; form.mimetype = ''; }
async function query() { if (!form.url.trim()) return; loading.value = true; try { const data = (await queryUrlMetadata(props.node, form.url.trim(), form.verifyCertificates)).data || {}; let filename = textValue(data.filename); let compression = '__default__'; if (props.content === 'iso') { const matches = filename.match(/^(.+)\.(gz|lzo|zst|bz2)$/i); if (matches) { filename = matches[1] || filename; compression = (matches[2] || '').toLowerCase(); } } if (props.content === 'import' && filename.endsWith('.img')) filename += '.raw'; Object.assign(form, { filename, size: Number(data.size) || 0, mimetype: textValue(data.mimetype), compression }); } finally { loading.value = false; } }
async function download() { if (!form.url.trim() || !form.filename.trim()) return; loading.value = true; try { const data: Record<string, unknown> = { content: props.content, url: form.url.trim(), filename: form.filename.trim(), 'verify-certificates': form.verifyCertificates ? 1 : 0, ...(props.content === 'iso' ? { compression: form.compression } : {}), ...(form.checksumAlgorithm !== '__default__' ? { 'checksum-algorithm': form.checksumAlgorithm, checksum: form.checksum.trim() } : {}) }; const upid = String((await downloadStorageUrl(props.node, props.storage, data)).data || ''); model.value = false; emit('task', upid); } finally { loading.value = false; } }
watch(model, (visible) => { if (visible) Object.assign(form, { url: '', filename: '', size: 0, mimetype: '', checksumAlgorithm: '__default__', checksum: '', verifyCertificates: true, compression: '__default__' }); });
watch([() => form.url, () => form.verifyCertificates], clearMetadata);
</script>
<template><q-dialog v-model="model" persistent><UWindow :title="gettext('Download from URL')" width="480px" :loading="loading"><div class="q-pa-md q-gutter-md"><div class="row no-wrap q-gutter-sm"><q-input v-model="form.url" dense outlined class="col" :label="gettext('URL')" /><q-btn no-caps outline :label="gettext('Query URL')" @click="query" /></div><q-input v-model="form.filename" dense outlined :label="gettext('File name')" /><div>{{ gettext('File size') }}: {{ form.size ? formatBytes(form.size) : '-' }}</div><div>{{ gettext('MIME type') }}: {{ form.mimetype || '-' }}</div><q-select v-model="form.checksumAlgorithm" dense outlined emit-value map-options :label="gettext('Hash algorithm')" :options="[{ label: gettext('none'), value: '__default__' }, { label: 'SHA256', value: 'sha256' }, { label: 'SHA512', value: 'sha512' }, { label: 'MD5', value: 'md5' }]" /><q-input v-model="form.checksum" dense outlined :disable="form.checksumAlgorithm === '__default__'" :label="gettext('Checksum')" /><q-checkbox v-model="form.verifyCertificates" dense :label="gettext('Verify certificates')" /><q-select v-if="content === 'iso'" v-model="form.compression" dense outlined emit-value map-options :label="gettext('Decompression algorithm')" :options="[{ label: gettext('none'), value: '__default__' }, { label: 'LZO', value: 'lzo' }, { label: 'GZIP', value: 'gz' }, { label: 'ZSTD', value: 'zst' }, { label: 'BZIP2', value: 'bz2' }]" /></div><template #foot><q-btn v-close-popup no-caps flat :label="gettext('Cancel')" /><q-btn no-caps flat color="primary" :disable="!form.url.trim() || !form.filename.trim() || (form.checksumAlgorithm !== '__default__' && !form.checksum.trim())" :label="gettext('Download')" @click="download" /></template></UWindow></q-dialog></template>
