import type { RouteRecordRaw } from 'vue-router';

const routes: RouteRecordRaw[] = [
  {
    path: '/login',
    name: 'user-login',
    component: () => import('@/pages/LoginPage.vue'),
    meta: { public: true, title: 'Login' },
  },
  {
    path: '/',
    redirect: '/dashboard',
    component: () => import('@/layouts/MainLayout.vue'),
    meta: { auth: true },
    children: [
      {
        path: 'dashboard',
        name: 'dashboard',
        component: () => import('@/pages/dashboard/DashboardPage.vue'),
        meta: { auth: true, title: 'Dashboard' },
      },
      {
        path: 'system/service',
        name: 'system-service',
        component: () => import('@/pages/system/ServicePage.vue'),
        meta: { auth: true, title: 'Service' },
      },
      {
        path: 'system/users',
        name: 'system-users',
        component: () => import('@/pages/system/UsersPage.vue'),
        meta: { auth: true, title: 'Users' },
      },
      {
        path: 'system/groups',
        name: 'system-groups',
        component: () => import('@/pages/system/GroupsPage.vue'),
        meta: { auth: true, title: 'Groups' },
      },
      {
        path: 'system/permissions',
        name: 'system-permissions',
        component: () => import('@/pages/system/PermissionPage.vue'),
        meta: { auth: true, title: 'Permissions' },
      },
      {
        path: 'system/pools',
        name: 'system-pools',
        component: () => import('@/pages/system/PoolsPage.vue'),
        meta: { auth: true, title: 'Pools' },
      },
      {
        path: 'system/options',
        name: 'system-options',
        component: () => import('@/pages/system/OptionPage.vue'),
        meta: { auth: true, title: 'Options' },
      },
      {
        path: 'system/metric-server',
        name: 'system-metric-server',
        component: () => import('@/pages/system/MetricServerPage.vue'),
        meta: { auth: true, title: 'Metric Server' },
      },
      {
        path: 'system/firewall',
        name: 'system-firewall',
        component: () => import('@/pages/system/FirewallPage.vue'),
        meta: { auth: true, title: 'Firewall' },
      },
      {
        path: 'system/sdn/zones',
        name: 'system-sdn-zones',
        component: () => import('@/pages/system/sdn/ZonesPage.vue'),
        meta: { auth: true, title: 'SDN Zones' },
      },
      {
        path: 'system/sdn/vnets',
        name: 'system-sdn-vnets',
        component: () => import('@/pages/system/sdn/VnetsPage.vue'),
        meta: { auth: true, title: 'SDN VNets' },
      },
      {
        path: 'system/sdn/ipam',
        name: 'system-sdn-ipam',
        component: () => import('@/pages/system/sdn/IpamPage.vue'),
        meta: { auth: true, title: 'SDN IPAM' },
      },
      {
        path: 'system/sdn/options',
        name: 'system-sdn-options',
        component: () => import('@/pages/system/sdn/SdnOptionsPage.vue'),
        meta: { auth: true, title: 'SDN Options' },
      },
      {
        path: 'system/permission/users',
        name: 'system-permission-users',
        component: () => import('@/pages/system/permission/PermissionUsersPage.vue'),
        meta: { auth: true, title: 'Users' },
      },
      {
        path: 'system/permission/groups',
        name: 'system-permission-groups',
        component: () => import('@/pages/system/permission/PermissionGroupsPage.vue'),
        meta: { auth: true, title: 'Groups' },
      },
      {
        path: 'system/permission/roles',
        name: 'system-permission-roles',
        component: () => import('@/pages/system/permission/RolesPage.vue'),
        meta: { auth: true, title: 'Roles' },
      },
      {
        path: 'system/permission/realm',
        name: 'system-permission-realm',
        component: () => import('@/pages/system/permission/RealmPage.vue'),
        meta: { auth: true, title: 'Realm' },
      },
      {
        path: 'system/permission/api-tokens',
        name: 'system-permission-api-tokens',
        component: () => import('@/pages/system/permission/APITokensPage.vue'),
        meta: { auth: true, title: 'APITokens' },
      },
      {
        path: 'storage/disks',
        name: 'storage-disks',
        component: () => import('@/pages/storage/DisksPage.vue'),
        meta: { auth: true, title: 'Disks Management' },
      },
      {
        path: 'storage/overview',
        name: 'storage-overview',
        component: () => import('@/pages/storage/OverviewPage.vue'),
        meta: { auth: true, title: 'Overview' },
      },
      {
        path: 'storage/udos',
        name: 'storage-ceph',
        component: () => import('@/pages/storage/CephPage.vue'),
        meta: { auth: true, title: 'Cluster Storage' },
      },
      {
        path: 'storage/disks/disk',
        name: 'storage-disks-disk',
        component: () => import('@/pages/storage/disks/DiskPage.vue'),
        meta: { auth: true, title: 'Disk' },
      },
      {
        path: 'storage/disks/directory',
        name: 'storage-disks-directory',
        component: () => import('@/pages/storage/disks/DirectoryPage.vue'),
        meta: { auth: true, title: 'Directory' },
      },
      {
        path: 'storage/disks/lvm',
        name: 'storage-disks-lvm',
        component: () => import('@/pages/storage/disks/LVMPage.vue'),
        meta: { auth: true, title: 'LVM' },
      },
      {
        path: 'storage/disks/lvmthin',
        name: 'storage-disks-lvmthin',
        component: () => import('@/pages/storage/disks/LVMThinPage.vue'),
        meta: { auth: true, title: 'LVMThin' },
      },
      {
        path: 'storage/disks/zfs',
        name: 'storage-disks-zfs',
        component: () => import('@/pages/storage/disks/ZFSPage.vue'),
        meta: { auth: true, title: 'ZFS' },
      },
      {
        path: 'storage/list',
        name: 'storage-list',
        component: () => import('@/pages/storage/StorageListPage.vue'),
        meta: { auth: true, title: 'Storage Services' },
      },
      {
        path: 'computer/iso',
        name: 'computer-iso',
        component: () => import('@/pages/computer/IsoPage.vue'),
        meta: { auth: true, title: 'ISO Image' },
      },
      {
        path: 'computer/overview',
        name: 'computer-overview',
        component: () => import('@/pages/computer/OverviewPage.vue'),
        meta: { auth: true, title: 'Overview' },
      },
      {
        path: 'computer/images',
        name: 'computer-images',
        component: () => import('@/pages/computer/ImagesPage.vue'),
        meta: { auth: true, title: 'Disk Image' },
      },
      {
        path: 'host/cluster',
        name: 'host-cluster',
        component: () => import('@/pages/host/ClusterPage.vue'),
        meta: { auth: true, title: 'Cluster' },
      },
      {
        path: 'host/overview',
        name: 'host-overview',
        component: () => import('@/pages/host/OverviewPage.vue'),
        meta: { auth: true, title: 'Overview' },
      },
      {
        path: 'maintenance/tasks',
        name: 'maintenance-tasks',
        component: () => import('@/pages/maintenance/TasksPage.vue'),
        meta: { auth: true, title: 'Tasks' },
      },
      {
        path: 'maintenance/logs',
        name: 'maintenance-logs',
        component: () => import('@/pages/maintenance/LogsPage.vue'),
        meta: { auth: true, title: 'Logs' },
      },
      {
        path: ':section/:page',
        name: 'shell-placeholder',
        component: () => import('@/pages/shell/PlaceholderPage.vue'),
        meta: { auth: true },
      },
    ],
  },
  {
    path: '/:catchAll(.*)*',
    component: () => import('@/pages/ErrorNotFound.vue'),
  },
];

export default routes;
