<script setup lang="ts">
import { computed, reactive, watch } from 'vue';
import UWindow from '@/components/UWindow.vue';
import { saveSdnPrefixListEntry } from '@/api/sdn';
import type { PveRecord } from '@/api/resources';
import { gettext } from '@/locale';

defineOptions({ name: 'CtPrefixListEntryEditor' });

const RE_IPV4_CIDR =
  /^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(?:[0-9]|[12][0-9]|3[0-2])$/;
const RE_IPV6_CIDR =
  /^(?:(?:[0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,7}:|(?:[0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|(?:[0-9a-fA-F]{1,4}:){1,5}(?::[0-9a-fA-F]{1,4}){1,2}|(?:[0-9a-fA-F]{1,4}:){1,4}(?::[0-9a-fA-F]{1,4}){1,3}|(?:[0-9a-fA-F]{1,4}:){1,3}(?::[0-9a-fA-F]{1,4}){1,4}|(?:[0-9a-fA-F]{1,4}:){1,2}(?::[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:(?:(?::[0-9a-fA-F]{1,4}){1,6})|:(?:(?::[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(?::[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(?:ffff(?::0{1,4}){0,1}:){0,1}(?:(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])|(?:[0-9a-fA-F]{1,4}:){1,4}:(?:(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(?:25[0-5]|(?:2[0-4]|1{0,1}[0-9]){0,1}[0-9]))\/(?:12[0-8]|1[01][0-9]|[1-9]?[0-9])$/;

const cidrRule = (v: string) =>
  !v || RE_IPV4_CIDR.test(v) || RE_IPV6_CIDR.test(v) || gettext('Invalid CIDR address');

const visible = defineModel<boolean>({ default: false });
const loading = defineModel<boolean>('loading', { default: false });
const props = defineProps<{
  prefixListId: string;
  seq?: string | number | undefined;
  entryData?: PveRecord | undefined;
}>();
const emit = defineEmits<{ saved: [] }>();

const isCreate = computed(() => props.seq === undefined);

const form = reactive({
  seq: '',
  action: 'permit',
  prefix: '',
  le: '',
  ge: '',
});

function reset(data: PveRecord = {}) {
  const v = (key: string) => data[key];
  Object.assign(form, {
    seq: v('seq') !== undefined && v('seq') !== null ? String(v('seq')) : '',
    action: v('action') || 'permit',
    prefix: v('prefix') || '',
    le: v('le') !== undefined && v('le') !== null ? String(v('le')) : '',
    ge: v('ge') !== undefined && v('ge') !== null ? String(v('ge')) : '',
  });
}

watch(visible, (open) => {
  if (!open) return;
  reset(props.entryData || {});
});

function cleanPayload() {
  const data: PveRecord = {
    action: form.action,
    prefix: form.prefix.trim(),
  };
  const deleted: string[] = [];

  if (form.seq.trim()) {
    data.seq = Number(form.seq);
  } else if (!isCreate.value) {
    deleted.push('seq');
  }

  if (form.le.trim()) {
    data.le = Number(form.le);
  } else if (!isCreate.value) {
    deleted.push('le');
  }

  if (form.ge.trim()) {
    data.ge = Number(form.ge);
  } else if (!isCreate.value) {
    deleted.push('ge');
  }

  if (deleted.length) data.delete = deleted;
  return data;
}

const formValid = computed(() => {
  if (!form.prefix.trim()) return false;
  if (cidrRule(form.prefix.trim()) !== true) return false;
  if (form.seq.trim()) {
    const n = Number(form.seq);
    if (!Number.isInteger(n) || n < 1) return false;
  }
  if (form.le.trim()) {
    const n = Number(form.le);
    if (!Number.isInteger(n) || n < 0 || n > 128) return false;
  }
  if (form.ge.trim()) {
    const n = Number(form.ge);
    if (!Number.isInteger(n) || n < 0 || n > 128) return false;
  }
  return true;
});

async function save() {
  if (!formValid.value) return;
  loading.value = true;
  try {
    await saveSdnPrefixListEntry(props.prefixListId, props.seq, cleanPayload());
    visible.value = false;
    emit('saved');
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <q-dialog v-model="visible" persistent>
    <UWindow
      :title="`${isCreate ? gettext('Add') : gettext('Edit')}: ${gettext('Prefix List Entry')}`"
      width="520px"
      :loading="loading"
    >
      <div class="q-pa-md u-dense">
        <div class="u-border q-pa-md">
          <q-input
            v-model="form.seq"
            dense
            type="number"
            min="1"
            step="1"
            :label="gettext('Sequence Nr.')"
            :placeholder="gettext('autogenerated')"
          />
          <q-select
            v-model="form.action"
            dense
            emit-value
            map-options
            :options="[
              { label: gettext('Permit'), value: 'permit' },
              { label: gettext('Deny'), value: 'deny' },
            ]"
            :label="gettext('Action')"
          />
          <q-input
            v-model="form.prefix"
            dense
            :label="gettext('Prefix')"
            :rules="[cidrRule]"
            lazy-rules
            :error="!form.prefix.trim()"
            :error-message="gettext('This field is required')"
          />
          <div class="row q-col-gutter-md q-mt-xs">
            <div class="col-6">
              <q-input
                v-model="form.le"
                dense
                type="number"
                min="0"
                max="128"
                step="1"
                :label="gettext('Prefix <=')"
              />
            </div>
            <div class="col-6">
              <q-input
                v-model="form.ge"
                dense
                type="number"
                min="0"
                max="128"
                step="1"
                :label="gettext('Prefix >=')"
              />
            </div>
          </div>
        </div>
      </div>
      <template #foot>
        <q-btn
          v-close-popup
          no-caps
          outline
          size="12px"
          class="u-button"
          :label="gettext('Cancel')"
        />
        <q-btn
          no-caps
          flat
          size="12px"
          class="bg-primary text-grey-1 u-button"
          :disable="!formValid"
          :label="isCreate ? gettext('Create') : gettext('OK')"
          @click="save"
        />
      </template>
    </UWindow>
  </q-dialog>
</template>
